version: '3'

networks:
  monitor-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules:/alertmanager/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitor-net
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    privileged: true
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
    ports:
      - '9093:9093'

  grafana:
    image: grafana/grafana:latest
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/data/grafana
    ports: 
      - '3000:3000'
    networks:
      - monitor-net